# Generated by Django 3.2.13 on 2022-04-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220423_1046'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='state',
        ),
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('book_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_book', to='book.books')),
                ('owner', models.ManyToManyField(null=True, related_name='owner_book', to='user.User')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_book', to='book.books')),
            ],
        ),
    ]
