# Generated by Django 3.2.13 on 2022-04-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220423_1046'),
        ('book', '0002_auto_20220425_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestbook',
            name='owner',
        ),
        migrations.AddField(
            model_name='requestbook',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_book', to='user.user'),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_request', to='book.books'),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
