# Generated by Django 3.2.13 on 2022-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220425_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('assigned', 'assigned'), ('pending', 'pending'), ('rejected', 'rejected'), ('closed', 'closed')], default='assigned', max_length=20),
        ),
    ]
