# Generated by Django 3.2.13 on 2022-04-26 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_requestbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 5, 55, 5, 748342)),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('assigned', 'assigned'), ('pending', 'pending'), ('rejected', 'rejected'), ('closed', 'closed')], default='pending', max_length=20),
        ),
    ]
