# Generated by Django 3.2.13 on 2022-04-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220426_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 6, 48, 54, 750337)),
        ),
    ]
