# Generated by Django 3.2.13 on 2022-04-26 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220423_1046'),
        ('book', '0006_alter_requestbook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ManyToManyField(related_name='user_books', to='user.User'),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 7, 14, 43, 550848)),
        ),
    ]
