# Generated by Django 3.2.13 on 2022-05-02 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220502_0554'),
        ('book', '0007_auto_20220426_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_state', to='user.state'),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 5, 54, 54, 424616)),
        ),
    ]
