# Generated by Django 3.2.13 on 2022-05-02 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220502_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 5, 55, 55, 829788)),
        ),
    ]
