# Generated by Django 3.2.13 on 2022-05-02 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_requestbook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 5, 57, 22, 493831)),
        ),
    ]
